[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[server]
follow_symlink = false
browser = "default"

[keymap]
preset = "vim"

[keymap.overrides]

[diagnostics]

[snippets]
include_default_snippets = true
custom_paths = []

[ai]
rules = ""
[ai.google]

[ai.open_ai]

[ai.anthropic]

[completion]
copilot = false
activate_on_typing = true

[package_management]
manager = "pip"

[runtime]
auto_instantiate = false
reactive_tests = true
on_cell_change = "lazy"
watcher_on_save = "lazy"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
auto_reload = "lazy"

[display]
default_table_page_size = 10
cell_output = "above"
dataframes = "rich"
default_width = "medium"
theme = "system"
code_editor_font_size = 14

[formatting]
line_length = 79

[language_servers.pylsp]
enable_pylint = false
enabled = true
enable_mypy = true
enable_flake8 = false
enable_pyflakes = false
enable_pydocstyle = false
enable_ruff = true

[experimental]
